name: Solar system workflow
on:
    workflow_dispatch: 
    push:
        branches: 
            - main
            - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}           
jobs:
    unit-testing:
        name: unit-testing
        strategy:
          matrix:
            nodejs_version: [18,19,20]
            operating_systems: [ubuntu-latest,macos-latest]
            exclude:
              - nodejs_version: 18
                operating_systems: macos-latest
        runs-on: ${{matrix.operating_systems}}
        steps:
        - name: checkout repository
          uses: actions/checkout@v4

        - name: Setup Nodejs Version - ${{matrix.nodejs_version}}
          uses: actions/setup-node@v4
          with:
            node-version: ${{matrix.nodejs_version}}

        - name: Install Depedencies
          run: npm install 

        - name: Unit testing
          run: npm test 

        - name: Archive test result
          uses: actions/upload-artifact@v4
          with:
            name: Moacha-test-result
            path: test-results.xml